### ISSUE TITLE
Need more robust approach

### ISSUE THREAD

**Issue by vovayartsev** [Rosa-Fox/naive-ticket#1]
Hey Rosa!

Thanks for implementing the solution. I really like your minimalistic approach and test-driven approach. However it needs to handle all possible edge-cases (well.... as much as you can). 

From the requirements:

```
At the very least, these rules should be enforced:
 - There are only 5 tickets available. Don’t oversell !!!
...
 - For each sold ticket exactly one charge should occur (i.e. don’t give a ticket for free and don’t let the users pay twice even if they press “back” in the browser)
```

**ISSUE 1**:  It's possible to oversell if you scale up you app horizontally at Heroku, and another user makes the reservation between these 2 lines 
```
    5 - Ticket.count
    # another client made a purchase here
    ticket.save
```

**ISSUE 2**: I was able to pay twice for the same ticket by copy-pasting the URL from a payment form page and opening it in a new tab

**ISSUE 3**: I was testing successful flow (purchasing tickets one by one, with the guest names Vova, Ivan, Roman, Nick, Alice, in this order). Everything was smooth (from end-user perspective), and each time I was getting a confirmation (except for Ivan - the UI got stuck). But when I went to the Guestlist, I saw there's no ticket for Alice (who got the confirmation), and there's a ticket for Ivan (who didn't get a confirmation):
![image](https://user-images.githubusercontent.com/204231/69794370-913a8000-11e3-11ea-947e-b0d79c209a07.png)

**ISSUE 4**: [BONUS] If somebody making many attempts (an evil guy, or just someone with an empty credit cards) reserves all tickets, the sales will stop. Your UI reads `We have reserved your ticket for 5 minutes`, but when I returned 5 minutes later I still was not able to purchase a ticket.

**Could you please work on the robustness of your solution?**

**Comment by Rosa-Fox** [comment]
Hi @vovayartsev,

Thank you so much for taking the time to review. Sorry for the delay, I had a very busy weekend. 

In regards to Issue 1... as far as I can tell the validation on the `Ticket` model would prevent over selling. I am not sure how horizontal scaling would effect this, but would be great if you could let me know how so I can improve in future :)

Issue 2... I fixed this, then broke it, then fixed it again... you will see from the commits.

Issue 3... ahh! This was an issue due to the ticket status not being update on purchase due to the `sold_out` validation. This is now fixed.

Issue 4... I have implemented. It seems a bit hacky though :(  how would you usually implement something like this?

**Comment by vovayartsev** [comment]
Thanks Rosa!

 **how horizontal scaling would effect this**

when multiple replicas of the app work at the same time, a race condition may happen.
In-app validation doesn't guarantee consistency in such scenarios - you need to either use `LOCK` (optimistic or pessimistic), or rely on DB constraints.

**re: pay twice**

We use a combination of:
1) `idempotency` guarantees of 3-rd party services. E.g. Stripe accepts [Idempotency Key](https://stripe.com/docs/api/idempotent_requests) on all requests - as a result, two subsequent API calls succeed, but the money is not taken twice 
2) DB transactions. The ticket purchase either fully succeeds or fails, but never leaves the DB in inconsistent state
3) Stripe webhooks - so that a successful payment in Stripe eventually results in issuing a ticket. 
Even if the UI gets broken (client, network or infrastructure issue), the user receives a confirmation e-mail and can find their tickets in the app.

**how would you usually implement something like this?**

we simply have `reserved_until` date-time column on a ticket
